apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: base-api
  name: base-api
spec:
  containers:
  - args:
    - yarn
    - start
    image: base-api-node
    name: base-api
    ports:
    - containerPort: 3000
    resources: {}
  restartPolicy: OnFailure
status: {}
